version: '3.8'

services:
  # Standalone Redis (for testing)
  redis-standalone:
    image: redis:8-alpine
    container_name: redis-standalone
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
    networks:
      - redis-net

  # Redis Cluster (6 nodes: 3 masters, 3 replicas)
  redis-node-1:
    image: redis:8-alpine
    container_name: redis-cluster-node-1
    ports:
      - "7000:7000"
      - "17000:17000"
    command: >
      redis-server
      --port 7000
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --save ""
    networks:
      - redis-net

  redis-node-2:
    image: redis:8-alpine
    container_name: redis-cluster-node-2
    ports:
      - "7001:7001"
      - "17001:17001"
    command: >
      redis-server
      --port 7001
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --save ""
    networks:
      - redis-net

  redis-node-3:
    image: redis:8-alpine
    container_name: redis-cluster-node-3
    ports:
      - "7002:7002"
      - "17002:17002"
    command: >
      redis-server
      --port 7002
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --save ""
    networks:
      - redis-net

  redis-node-4:
    image: redis:8-alpine
    container_name: redis-cluster-node-4
    ports:
      - "7003:7003"
      - "17003:17003"
    command: >
      redis-server
      --port 7003
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --save ""
    networks:
      - redis-net

  redis-node-5:
    image: redis:8-alpine
    container_name: redis-cluster-node-5
    ports:
      - "7004:7004"
      - "17004:17004"
    command: >
      redis-server
      --port 7004
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --save ""
    networks:
      - redis-net

  redis-node-6:
    image: redis:8-alpine
    container_name: redis-cluster-node-6
    ports:
      - "7005:7005"
      - "17005:17005"
    command: >
      redis-server
      --port 7005
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --save ""
    networks:
      - redis-net

  # Cluster init service
  redis-cluster-init:
    image: redis:8-alpine
    container_name: redis-cluster-init
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    command: >
      sh -c "
        sleep 5 &&
        redis-cli --cluster create
        redis-node-1:7000
        redis-node-2:7001
        redis-node-3:7002
        redis-node-4:7003
        redis-node-5:7004
        redis-node-6:7005
        --cluster-replicas 1
        --cluster-yes
      "
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
